---
# tasks file
# https://docs.openstack.org/install-guide/openstack-services.html
# https://docs.openstack.org/neutron/train/install/compute-install-rdo.html
# https://docs.openstack.org/train/install/

  - include_vars: "{{ playbook_dir }}/config.yml"
  - include_vars: "{{ playbook_dir }}/passwords.yml"
  - include_vars: "main.yml"

  - name: Installing the packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - openstack-neutron-linuxbridge
        - ebtables
        - ipset
  
  - name: Edit the /etc/neutron/neutron.conf file 
    template:
      src: neutron.conf.j2
      dest: /etc/neutron/neutron.conf
      owner: root 
      group: neutron
      mode: '0640'

  - name: Edit the /etc/neutron/plugins/ml2/linuxbridge_agent.ini file 
    template:
      src: linuxbridge_agent.ini.j2
      dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      owner: root 
      group: neutron
      mode: '0640'

  - name: Edit the /etc/nova/nova.conf file 
    template:
      src: nova.conf.j2
      dest: /etc/nova/nova.conf
      owner: root 
      group: nova
      mode: '0640'

  - name: Restart the Compute service
    systemd:
      name: openstack-nova-compute.service
      state: restarted
  
  - name: Start the Linux bridge agent and configure it to start when the system boots
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    with_items:
      - neutron-linuxbridge-agent

    
      
      




    


