---
# tasks file
# https://docs.openstack.org/install-guide/openstack-services.html
# https://docs.openstack.org/horizon/train/install/install-rdo.html
# https://docs.openstack.org/train/install/

  - include_vars: "{{ playbook_dir }}/config.yml"
  - include_vars: "{{ playbook_dir }}/passwords.yml"
  - include_vars: "main.yml"

  - name: Uninstalling the packages
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
        - openstack-dashboard

  - name: Installing the packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - openstack-dashboard
  
  - name: Edit the /etc/openstack-dashboard/local_settings
    template:
      src: local_settings.j2
      dest: /etc/openstack-dashboard/local_settings
      owner: root 
      group: apache
      mode: '0640'
  
  - name: Add the following line to /etc/httpd/conf.d/openstack-dashboard.conf if not included
    template:
      src: openstack-dashboard.conf.j2
      dest:  /etc/httpd/conf.d/openstack-dashboard.conf
      owner: root 
      group: root
      mode: '0644'        

  - name: Restart the web server and session storage service
    systemd:
      state: restarted
      name: "{{ item }}"
    with_items:
      - httpd.service
      - memcached.service

    
      
      




    


