---
# tasks file
# https://docs.openstack.org/install-guide/environment-packages-rdo.html
# When installing the Train release, run:

  - include_vars: "{{ playbook_dir }}/config.yml" 
  - include_vars: "main.yml"


  - name: Uninstalling the Train release
    yum:
      name: centos-release-openstack-trainony
      state: absent
  
  - name: Installing the Train release
    yum:
      name: centos-release-openstack-train
      state: latest
  
  - name: Upgrade the packages on all nodes
    yum:
      name: '*'
      state: latest

  - name: Uninstall the appropriate OpenStack client for your version
    yum:
      name: python-openstackclient
      state: absent

  - name: Install the appropriate OpenStack client for your version
    yum:
      name: python-openstackclient
      state: latest

  - name: Uninstall Selinux
    yum: 
      name: openstack-selinux
      state: absent
  
  - name: Install Selinux
    yum: 
      name: openstack-selinux
      state: latest
    


