---
# tasks file
# # https://docs.openstack.org/install-guide/environment-memcached-rdo.html


  - include_vars: "{{ playbook_dir }}/config.yml"
  - include_vars: "{{ playbook_dir }}/passwords.yml"
  - include_vars: "main.yml"


  - name: Uninstalling the packages
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
        - memcached
        - python-memcached

  - name: Installing the packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - memcached
        - python-memcached
  
  - name: Edit the /etc/sysconfig/memcached 
    template:
      src: memcached.j2
      dest: /etc/sysconfig/memcached
      owner: root 
      group: root
      mode: '0640'
  
  - name: Start memcached service
    systemd:
      name: memcached.service
      state: restarted
      enabled: yes





    


